export const specialName = [
  "Naga Bonar",
  "Roro Jonggrang",
  "Sapi FPP",
  "Raja Iblis",
  "Ratu Kupu-kupu",
  "Tas Laptop",
  "Malika",
  "Raksasa Hijau",
  "Gajah Mekanik",
  "Rusdi Imut",
  "Kosong",
  "Daffa Shitposting",
  "Singa Introvert",
  "Siluman Hitam",
  "Kecoa Glowup",
  "Kaos FF",
  "Kasir Indomaret",
  "Pat Kai",
  "Plastik Hitam",
  "Laba-laba Sunda",
  "Bakwan Jagung",
  "Kertas HTS",
  "Polisi Bangun",
  "Cireng Pedes",
  "Bagas Dribble",
  "Jok Kotor",
  "Iphone 12 Pro Max",
  "Pemuda Pancasila",
  "Carlos Doang",
  "Bot Menfess",
  "Kulkas 2 Pintu",
  "Pria Dekil",
  "Kosong",
  "Petir Abadi",
  "Agus Februari",
  "Kerupuk Kaleng",
  "Charger Iphone",
  "Pemuda 27 Mei",
  "Tiktokers Kondang",
  "Domba Ganteng",
  "Harimau Sumbing",
  "Badut Mixue",
  "TWS Ikan",
  "Ryan Gosling",
  "Jawline Sigma",
  "Kura-kura Mewing",
  "Undur-Undur Maju",
  "Kominfo",
  "Bapak Gemoy",
  "Desa Han",
  "Anakan Jing",
  "Burjo Kebumen",
  "Kucing Goreng",
  "Asbak Bali",
];
