export const specialName = [
  "Naga Bonar",
  "Roro Jonggrang",
  "Sapi FPP",
  "Raja Iblis",
  "Tas Laptop Asus",
  "Malika",
  "Raksasa Hijau",
  "Gajah Mekanik",
  "Rusdi Imut",
  "Daffa Shitposting",
  "Singa Introvert",
  "Siluman Hitam",
  "Kecoa Glowup",
  "Kaos FF",
  "Kasir Indomaret",
  "Pat Kai",
  "Plastik Hitam",
  "Laba-laba Sunda",
  "Bakwan Jagung",
  "Kertas HTS",
  "Polisi Bangun",
  "Cireng Pedes",
  "Bagas Dribble",
  "Jok Kotor",
  "Iphone 12 Pro Max",
  "Pemuda Pancasila",
  "Carlos Doang",
  "Bot Menfess",
  "Mantapancing",
  "Duda Kaya",
  "Pria Dekil",
  "Petir Abadi",
  "Agus Februari",
  "Kerupuk Kaleng",
  "Charger Type C",
  "Pemuda 27 Mei",
  "Tiktokers Kondang",
  "Domba Ganteng",
  "Harimau Sumbing",
  "Badut Mixue",
  "Airpods KW",
  "Ryan Gosling",
  "Pesona Sigma",
  "Kura-kura Mewing",
  "Undur-Undur Maju",
  "Kominfo",
  "Presiden Gemoy",
  "Desa Han",
  "Anakan Jing",
  "Burjo Kebumen",
  "Kucing Goreng",
];
